const colors = {
  background: {
    default: '#f9f9f9',
  },
  black: '#2A2A2A',
  button: {
    default: { background: '#f6f6f6', color: '#2A2A2A' },
    destructive: { background: '#df1616', color: '#FFFFFF' },
    outlined: { background: 'transparent', borderColor: '#d2d2d2', color: '#2A2A2A' },
    primary: { background: '#4485f1', color: '#FFFFFF' },
    subtle: { background: 'transparent', color: '#4485f1' },
    subtleDefault: { background: 'transparent', color: '#2A2A2A' },
    subtleDestructive: { background: 'transparent', color: '#df1616' },
  },
  comments: {
    default: '#131415',
  },
  error: {
    dark: '#9c0f0f',
    darker: '#590909',
    darkest: '#2d0404',
    error: '#df1616',
    errorText: '#9C0F0F',
    light: '#e95c5c',
    lighter: '#f2a2a2',
    lightest: '#f9d0d0',
  },
  grey: {
    dark: '#3e3e3e',
    darker: '#2a2a2a',
    darkest: '#1a1a1a',
    light: '#d2d2d2',
    lighter: '#eeeeee',
    lightest: '#f6f6f6',
    lightly: '#E4E4E4',
    medium: '#909090',
    semi: '#b8b8b8',
  },
  issues: {
    verticalBar: '#FFBB38',
  },
  pitchBlack: '#000000',
  primary: {
    dark: '#396fc8',
    darker: '#285195',
    darkest: '#18315c',
    light: '#72a1f1',
    lighter: '#98b8ee',
    lightest: '#c9d7ed',
    primary: '#4485f1',
  },
  purple: {
    light: '#efe3f8',
  },
  rfis: {
    fieldBackground: '#f9f9f9',
    isOverdueBackground: '#FBE9E9',
    status: {
      Closed: '#d2d2d2',
      Draft: 'white',
      Expected: 'white',
      Forwarded: '#AF49EB',
      Open: '#52C770',
      Pending: 'white',
    },
    title: '#9a9a9a',
  },
  search: {
    focused: '#4485F1',
  },
  success: {
    dark: '#11832f',
    darker: '#055720',
    darkest: '#00230c',
    light: '#52c770',
    lighter: '#a2d1af',
    lightest: '#d5e7da',
    success: '#20c443',
  },
  switchButton: '#f4f3f4',
  text: '#2A2A2A',
  underlayColors: {
    dark: '#ddddddcc',
    pale: '#fffefed1',
  },
  warning: {
    dark: '#b38327',
    darker: '#664b16',
    darkest: '#33250b',
    light: '#ffcf74',
    lighter: '#ffe4af',
    lightest: '#fff1d7',
    warning: '#ffbb38',
  },
  white: '#FFFFFF',
};

export default colors;
